### PR TITLE
hypo: Fix playing a card during empathy

### LINKED ISSUE #1967: Playing a card in hypo during empathy says that you're trying to play an unknown card

### PR DESCRIPTION
**Pull request by timotree3**
Fixes #1967

### CODE REVIEW

**Comment by Zamiell** [comment]
shouldn't getSuitIndexFromNote() etc be in some notes.ts file and not on the hanabi card object

**Comment by timotree3** [comment]
probably

**Comment by timotree3** [comment]
good now?

**Comment by Zamiell** [comment]
looks good thanks

**Pull request merged**
