### PR TITLE
Stop the stack bases from flying around during replays

### PR DESCRIPTION
**Pull request by kemurphy**

### CODE REVIEW

**Comment by Zamiell** [comment]
this bug is already fixed on master, did you test it?

**Comment by rogers-j** [comment]
For what it's worth, I can reliably repro on the live site by middle-clicking a card after it has been clued.

**Comment by Zamiell** [comment]
the live site is on a commit from like 6-12 months ago

**Comment by kemurphy** [comment]
Indeed, this isn't a bug on master.  Why don't we keep the live site up to date?

**Comment by Zamiell** [comment]
right now the site is on an older commit temporarily because there are some problems remaining on the master branch that i still need to fix

**Comment by kemurphy** [comment]
Would these problems be the typecheck errors on master?

**Comment by Zamiell** [comment]
ya

**Comment by Zamiell** [comment]
yeah

**Pull request closed without merging**
