### PR TITLE
Take into account spaces before "(" and after ")"

### PR DESCRIPTION
**Pull request by DrAnax**

### CODE REVIEW

**Comment by Zamiell** [comment]
should we write some tests?

**Comment by DrAnax** [comment]
Possibly

**Comment by DrAnax** [comment]
Ah, I need to push the test in a separate PR first, right?

**Comment by Zamiell** [comment]
you can just do it in this one to make it easy

**Comment by Zamiell** [comment]
thanks

**Comment by Zamiell** [comment]
those are some good tests :)

**Pull request merged**
