### PR TITLE
Special keys removing the pipe are ignored the first time

### LINKED ISSUE #2344: when making a note, backspace works incorrectly
step 1 - make the following note on a card:
[y2] p

step 2 - right click the card again to bring up the note box

step 3 - press backspace

expected: only the pipe and space will be deleted
observed: the "p" character is deleted

### PR DESCRIPTION
**Pull request by DrAnax**
Closes #2344

### CODE REVIEW

**Comment by Zamiell** [comment]
doesn't this break the case of e.g. pressing home?

**Comment by DrAnax** [comment]
> doesn't this break the case of e.g. pressing home?

It ignores all of [Arrows, Home/End, Del, Backspace]. Want only some of those?

**Comment by Zamiell** [comment]
yes, home should go home.
the rest are fine as being a no-op.

**Comment by Zamiell** [comment]
probably

**Comment by Zamiell** [comment]
ok, lets try this out for a few days ><

**Pull request merged**
