### PR TITLE
Show start rank pip

### LINKED ISSUE #2202: Up or Down: Show on the backs of cards whether a card could be a Start card
In Up or Down, show on the backs of cards whether the card could be a Start card, for example, by showing an S to the left of the 1:
image

Even though users cannot directly clue Start cards, they would still be `X`'d out if the user can deduce that the card is not a Start card because they can see all the Start cards matching the possible suits

With this change, in the screenshot above the rightmost card is clearly the Green Five. Without this, the user has to remember to check whether it could also be the Green Start.

### PR DESCRIPTION
**Pull request by DarthGandalf**
Fix #2202
Selection_088
Selection_089

### CODE REVIEW

**Comment by Zamiell** [comment]
nice work

**Comment by timotree3** [comment]
Would it be possible to make it taller?

**Comment by Zamiell** [comment]
it would probably look better as a capital S, yeah

**Comment by DarthGandalf** [comment]
> Would it be possible to make it taller?

I'd like it to be taller. But for some strange reason (probably related to the font) when I use S instead of s, it doesn't render anything with font size 63. But it renders S fine with a smaller font size.

**Pull request merged**
