### PR TITLE
Hypo ui overhaul

### PR DESCRIPTION
**Pull request by Hyphen-ated**

### CODE REVIEW

**Comment by Zamiell** [comment]
can you capitalize all comments so that they match the existing style of the code

**Comment by Zamiell** [comment]
also remove all end-of-sentence-periods from comments for consistency

**Comment by Zamiell** [comment]
otherwise it looks good

**Comment by Hyphen-ated** [comment]
I have done this

**Comment by Zamiell** [comment]
excellent, thank you very much, this is a much needed change

**Pull request merged**
