### PR TITLE
Set cursor via class, not style

### PR DESCRIPTION
**Pull request by DrAnax**

### CODE REVIEW

**Comment by Zamiell** [comment]
much better, thank you

**Comment by Zamiell** [comment]
does this also fix the bug where it constantly asks the server for the new icon image?

**Comment by DrAnax** [comment]
Yes, that's the point

**Comment by Zamiell** [comment]
ok, nice.
its also better in code because style should be in a css file lol

**Comment by DrAnax** [comment]
Users need to reset cache or they won't see the changes

**Pull request merged**
