### PR TITLE
fix right click (arrows) on game area

### PR DESCRIPTION
**Pull request by DrAnax**
Turn label was unclickable (as well as set turn prompt)

### CODE REVIEW

**Comment by Zamiell** [comment]
oh can you make sure the 3 individual strike boxes are also right-clickable properly?

**Comment by Zamiell** [comment]
last time i checked this was bugged iirc

**Comment by DrAnax** [comment]
sure, hold on

**Comment by DrAnax** [comment]
bugged, fixing it

**Comment by Zamiell** [comment]
thanks

**Comment by Zamiell** [comment]
awesome thanks

**Pull request merged**
