### PR TITLE
Show number of online users in two tabs

### LINKED ISSUE #2371: request: move number of online people from the chat tab to users tab

### PR DESCRIPTION
**Pull request by DrAnax**
Closes #2371

### CODE REVIEW

**Comment by Zamiell** [comment]
why would we want to clutter the lobby with the word "online"?

**Comment by DrAnax** [comment]
> why would we want to clutter the lobby with the word "online"?

@Aigul9

**Comment by Aigul9** [comment]
not necessary to add "online"

**Comment by DrAnax** [comment]
This PR changed from this

image


to this

image

on small screens only

**Comment by DrAnax** [comment]
Do you want me to just remove the word "online" inside the parenthesis?

**Comment by Zamiell** [comment]
sure

**Pull request merged**
