### PR TITLE
Initialize hypo toggleRevealed correctly

### LINKED ISSUE #1747: 'Show Drawn Cards' is disabled
How to reproduce:
* Enter hypothetical mode.
* Discard/Play a card.
* Click 'Show Drawn Cards'.
* Give a clue, which touches the card just drawn.
-> 'Hide Drawn Cards' is disabled correctly.
* Leave hypothetical mode.
* Enter hypothetical mode.
-> 'Show Drawn Cards' is disabled.

The button should always be enabled when entering hypothetical mode.

### PR DESCRIPTION
**Pull request by padiwik**
Fix #1747 ; I hope this is the correct way

### CODE REVIEW

**Comment by Zamiell** [comment]
did you test it

**Comment by padiwik** [comment]
yes i did, i also tried some "have someone join a hypo midway" but i didn't do all of those cases

**Comment by Zamiell** [comment]
ok

**Comment by padiwik** [comment]
(the server-side change fixes the bug where clicking the button does nothing because client and server were desynced)

**Comment by Zamiell** [comment]
nice catch

**Pull request merged**
