### PR TITLE
Appending notes uses bracket syntax

### LINKED ISSUE #2108: Improve the cm, and f notes
I think i would be helpfull if the right click + ctrl or ALt writes [cm] [f] so we can just add up our notes without erasing the border .

### PR DESCRIPTION
**Pull request by newduke**
fixes #2108

### CODE REVIEW

**Comment by Zamiell** [comment]
no, we dont want to change this functionality

**Comment by Zamiell** [comment]
can you submit a pr instead that only looks for square brackets in the rightmost pipe section?
that fixes the problem without inserting a bunch of stupid brackets everywhere

**Comment by Zamiell** [comment]
i should of just programmed it that way from the beginning but i was a stupid person

**Comment by newduke** [comment]
Um. Why you close?

**Comment by Zamiell** [comment]
can you submit a pr instead that changes the note-logic to only search for square brackets in the rightmost pipe section?
that fixes the problem without inserting a bunch of stupid brackets everywhere

**Comment by padiwik** [comment]
That's a nice idea but does not fix the problem described in the linked issue.

**Comment by newduke** [comment]
@padiwik Why not? Please elaborate.

**Comment by padiwik** [comment]
@newduke If you write `cm | probably r3` or even `cm probably r3` then neither of these would work. In fact Zam's proposal breaks `[cm] | probably r3` (currently suggested in #1225) which might be undesirable.

**Comment by newduke** [comment]
don't you want `this is a note|[r2][cm]`?  The whole point is to not lose previous notes.

**Comment by padiwik** [comment]
The issue is when you need to append additional notes after doing ctrl + right click or whatever

**Comment by newduke** [comment]
Please refute `this is a note|[r2][cm]`

**Comment by Zamiell** [comment]
```
cm | probably r3
```
that's a wrong note, someone would instead write
```
[cm] probably r3
```

**Comment by padiwik** [comment]
> Please refute `this is a note|[r2][cm]`

Are you suggesting this as an alternative syntax? If you have a `cm` card and then need to mark it as `probably r3` you would not put that information before the `cm`. It should be like Zam pointed out.

**Comment by Zamiell** [comment]
and then, that would be piped when new actual information is received
e.g.
```
[cm] probably r3 | [cm] [r3]
```

**Comment by Zamiell** [comment]
> The issue is when you need to append additional notes after doing ctrl + right click or whatever

appending notes adds a pipe, therefore i dont see what you are getting at

**Comment by padiwik** [comment]
By appending notes I mean adding info like "probably r3", which I understand is different from some other contexts of appending where you do actually need a pipe.

**Comment by Zamiell** [comment]
im fine with that, people will learn the new syntax and adjust accordingly

**Comment by padiwik** [comment]
Sure, fine, but they still would need to manually add brackets to the note when adding info like `probably r3`. If the keyboard shortcuts automatically add brackets and brackets are only parsed on the right-most piped section, everything works well.

**Comment by Zamiell** [comment]
> they still would need to manually add brackets to the note when adding info like probably r3

this is how it currently is, so i dont follow

**Comment by padiwik** [comment]
> this is how it currently is, so i dont follow

This is the entire issue multiple people are complaining about, and which this PR is trying to fix.

**Comment by Zamiell** [comment]
this pr does not fix `probably r3`

**Comment by Zamiell** [comment]
the behavior for that note is unchanged

**Comment by padiwik** [comment]
With the PR: You start off with `[cm]` and you only need to add the text ` probably r3`.
Without the PR: You start off with `cm` and need to rewrite the entire note as `[cm] probably r3` which is silly.

**Comment by padiwik** [comment]
I should probably also share my opinions on what you call "needless" brackets. I believe `[f]` looks nicer than `f`, especially because it makes clear that this is special syntax that the game interprets a certain way. There's no downside to changing the keyboard shortcut to doing that, especially if we also add the "brackets only read in right-most section" thing. At any rate, a notion of note aesthetics should not prevent functionality that many people want.

**Comment by newduke** [comment]
So... reopen please?

**Comment by Zamiell** [comment]
ok i'll accept this but we also need the other pr too

**Comment by Zamiell** [comment]
i disagre that `[f]` "looks nicer" than `f`, i think it looks cluttered and stupid, but the other thing you said was convincing

**Comment by padiwik** [comment]
This is basically irrelevant but `f` just feels too naked or bare to me. For other notes like `[cm]` I can understand why it seems cluttered to you.

**Comment by Zamiell** [comment]
i love being naked

**Comment by Zamiell** [comment]
and bare

**Comment by Zamiell** [comment]
yes please can you do this pr https://github.com/Zamiell/hanabi-live/pull/2116#issuecomment-790909266

**Comment by newduke** [comment]
> yes please can you do this pr [#2116 (comment)](https://github.com/Zamiell/hanabi-live/pull/2116#issuecomment-790909266)

That is precisely what this PR does, no?

**Comment by padiwik** [comment]
If you have a note like `[foo] | [bar]` then only bar should be read.

**Comment by padiwik** [comment]
This is the PR Zam proposes. Presumably to allow appending notes such as `[cm]` -> `[cm] | not cm` and then the card is no longer cm.

**Pull request merged**
