### PR TITLE
fix shadow bug

### LINKED ISSUE #1736: bug with permanent raised shadows
step 1 - start a new game
step 2 - play a card from your hand
step 3 - go into the in-game replay
step 4 - click and hold on the you played, which will draw the shadow
step 5 - press the right arrow key so that the card plays on to the stacks

now, the card will be bugged forever, with the shadow permanently drawn

this functionality is defined here:
https://github.com/Zamiell/hanabi-live/blob/master/client/src/game/ui/HanabiCard.ts#L825-L871

the fix is to (probably) add more shit to the appropriate observer in StateObserver.ts

### PR DESCRIPTION
**Pull request by DrAnax**
Fixes #1736

### CODE REVIEW

**Comment by Zamiell** [comment]
what was the problem before?

**Comment by DrAnax** [comment]
1. I created a new pr because my previous branch didn't start from master
2. The latest update on UIReducer.ts requires HanabiCard.ts. Meanwhile, jest tests stateReducer.ts which now requires UIReducer.ts. This leads, eventually into requiring globals.ts for testing stateReducer.ts, but globals.ts has a navigator.userAgent test to check for Firefox. I ended up mocking UIReducer and the problem was solved.

**Comment by Zamiell** [comment]
interesting. nice work

**Comment by Zamiell** [comment]
horray for better state management

**Comment by DrAnax** [comment]
I will decouple all soon™

**Comment by Zamiell** [comment]
oh you mean the UI? or you mean other global variables?

**Comment by DrAnax** [comment]
stateReducer.test.ts ended up requiring globals.ts

**Pull request merged**
