### PR TITLE
Variant dropdown button restyle

### PR DESCRIPTION
**Pull request by vEnhance**
Requested by Zam

Mimic the "create game" button style and also clean a few things for consistency

### CODE REVIEW

**Comment by Zamiell** [comment]
for me, the button no longer works after this PR.
did you test this change?

**Comment by Zamiell** [comment]
nevermind it does work actually

**Comment by vEnhance** [comment]
Strangely, it works fine for me.

**Comment by Zamiell** [comment]
new feature looks good, thanks

**Pull request merged**
