### PR TITLE
[client] Fix shadow bug

### PR DESCRIPTION
**Pull request by DrAnax**
Code review & testing are welcome

### CODE REVIEW

**Comment by Zamiell** [comment]
looks fantastic.

now why is jest failing?

**Comment by Zamiell** [comment]
PASS src/game/reducers/cardsReducer.test.ts (10.235 s)
PASS src/game/reducers/gameStateReducer.test.ts
PASS src/game/rules/stats.test.ts
PASS src/game/rules/playStacks.test.ts
PASS src/game/reducers/integration.test.ts
PASS src/game/reducers/noteIdentity.test.ts
PASS src/game/reducers/turnReducer.test.ts
PASS src/game/reducers/cardPossibilitiesReducer.test.ts
FAIL src/game/reducers/replayReducer.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: navigator is not defined

      57 |   lastActiveElement: HTMLElement | null = null;
      58 | 
    > 59 |   browserIsFirefox = navigator.userAgent.toLowerCase().indexOf("firefox") > -1;
         |                      ^
      60 | }
      61 | 
      62 | const globals = new Globals();

      at new Globals (src/globals.ts:59:22)
      at Object.<anonymous> (src/globals.ts:62:17)
      at Object.<anonymous> (src/game/ui/globals.ts:6:1)

PASS src/game/rules/clueTokens.test.ts
PASS src/game/rules/deck.test.ts
FAIL src/game/reducers/stateReducer.test.ts
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/en/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: navigator is not defined

      57 |   lastActiveElement: HTMLElement | null = null;
      58 | 
    > 59 |   browserIsFirefox = navigator.userAgent.toLowerCase().indexOf("firefox") > -1;
         |                      ^
      60 | }
      61 | 
      62 | const globals = new Globals();

      at new Globals (src/globals.ts:59:22)
      at Object.<anonymous> (src/globals.ts:62:17)
      at Object.<anonymous> (src/game/ui/globals.ts:6:1)

PASS src/game/rules/variant.test.ts

Test Suites: 2 failed, 11 passed, 13 total
Tests:       217 passed, 217 total
Snapshots:   0 total
Time:        18.541 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hanab-live-client@0.0.1 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hanab-live-client@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-03-24T16_37_29_871Z-debug.log
Error: Process completed with exit code 1.

**Comment by DrAnax** [comment]
No idea; I didn't touch any jest configuration files. According to jest's logs:

ReferenceError: navigator is not defined
in _browserIsFirefox = navigator.userAgent.toLowerCase().indexOf("firefox") > -1;_

**Comment by Zamiell** [comment]
ill look into this

**Pull request closed without merging**
