### PR TITLE
Don't hide tooltips when a game action happens

### PR DESCRIPTION
**Pull request by padiwik**
Suppose Bob plays. If you're reading a note on Cathy's hand, you want to keep reading it. If you're reading a note on Bob's hand and the card moves, the note will automatically close when you move your mouse a bit.

### CODE REVIEW

**Comment by padiwik** [comment]
It has existed since initial commit https://github.com/Zamiell/hanabi-live/blame/9b2a50c21d29131fe27a952b97e06ddba7b51388/public/js/ui.js

**Comment by Zamiell** [comment]
this code is intentional, because it fixes the "bug" where:
1) Alice is hovering over Bob's slot 1 and reading the note that she has previously written there
2) Bob plays his slot 1 card, and the card moves from his hand to the play stacks
3) the note tooltip stays in place and is now hovered over the wrong card, the card that Bob just drew

**Comment by padiwik** [comment]
This is not an issue. If Alice wants to stop reading the note, she just needs to move her mouse a bit and it goes away.

**Comment by Zamiell** [comment]
ok then

**Pull request merged**
