### PR TITLE
Start game button disabled for 500 ms upon players leaving and joining

### PR DESCRIPTION
**Pull request by timotree3**
https://user-images.githubusercontent.com/6473438/103963716-f8856c00-5127-11eb-87d3-52fa51af0a90.mp4

### CODE REVIEW

**Comment by timotree3** [comment]
The server side changes should be easy enough for you to merge into your channels branch

**Comment by timotree3** [comment]
@Zamiell status on reviewing this?

**Comment by Zamiell** [comment]
i dont want to merge any server changes until the channels branch is merged

**Comment by timotree3** [comment]
I request you look at the code. It's mostly client, and the changes that are server-side would not conflict with the manager model

**Comment by Zamiell** [comment]
i looked at the code and it looks fine

**Comment by DrAnax** [comment]
This has already been implemented and merged via #2140

**Comment by timotree3** [comment]
except it was implemented such that the button is grayed out upon any change to the game state e.g. variant changing or players becoming "away"

**Comment by Zamiell** [comment]
looks like this is fixed in #2314

**Pull request closed without merging**
