### PR TITLE
Fix contrarian endgame stuff

### LINKED ISSUE #1933: Contrarian only grants 1 turn after deck runs out
Game ID 360103

### PR DESCRIPTION
**Pull request by timotree3**
Fixes #1933 
Tested that game JSON and I was able to play p5 and finish the game.

Testing now if normal games finish properly

### CODE REVIEW

**Comment by timotree3** [comment]
Actually, this shouldn't affect normal games since my new code only runs if there are detrimental characters. I guess then all there is to do is make sure the code looks right. i.e. no off-by-one errors in my for loop

**Comment by Zamiell** [comment]
looks like it fails ci

**Comment by Zamiell** [comment]
says that you need to delete an extra newline

**Comment by timotree3** [comment]
> says that you need to delete an extra newline

it doesn't give a location

**Comment by Zamiell** [comment]
its line 149, it should show you in vsode

**Comment by Zamiell** [comment]
it does for me

**Comment by Zamiell** [comment]
are you not using the linter? theres another blank line that the linter is complaining about that should be obvious if you just save the file and look in vscode

**Comment by timotree3** [comment]
Yeah the linter doesn't seem to be working. Neither is find all references. Come to think of it, the only Go thing that's working is autoformat

**Comment by Zamiell** [comment]
test to see if running `./server/lint_server.sh` works

**Comment by Zamiell** [comment]
find all references doesn't work for me either, i think thats only a typescript feature

**Comment by Zamiell** [comment]
thanks

**Pull request merged**
