### PR TITLE
Convert js keys to keycodes

### PR DESCRIPTION
**Pull request by DrAnax**

### CODE REVIEW

**Comment by DrAnax** [comment]
Closes #2077

**Comment by padiwik** [comment]
Isn't `event.which` deprecated?

**Comment by Zamiell** [comment]
thanks

**Comment by Zamiell** [comment]
can you submit PR for server too?

**Comment by Zamiell** [comment]
https://github.com/jquery/jquery/issues/4755#issuecomment-664501730

**Comment by DrAnax** [comment]
yes

**Pull request merged**
