### PR TITLE
Future eff tests

### PR DESCRIPTION
**Pull request by timotree3**

### CODE REVIEW

**Comment by timotree3** [comment]
hmm it looks glitchy as you use it. as you discard, the future efficiency flickers down a bit and then up, maybe it is lowering the pace by one, updating the efficiency, and then gaining a clue and updating it again?

**Comment by Zamiell** [comment]
no idea, start putting in breakpoints or something

**Comment by Zamiell** [comment]
or put in a shitload of console.log everywhere

**Comment by Zamiell** [comment]
[ ] add tests for all of the interesting stats functions besides doubleDiscard
[ ] fix pace with contrarian
[ ] fix pace + efficiency with all or nothing

**Comment by timotree3** [comment]
> add tests for all of the interesting stats functions besides doubleDiscard
this is harder than I thought because everything is intermingled with statsReducer. Maybe I should write tests for statsreducer?

**Comment by Zamiell** [comment]
not sure what you mean - there are already integration tests, add more of those if you want?

**Comment by timotree3** [comment]
well to do those in the same style I would have to generate a game JSON that would trigger the past bug

**Comment by Zamiell** [comment]
add the file statsReducer.test.ts and add tests to it i guess

**Comment by Zamiell** [comment]
actually no because it needs an entire game state, so you cant test the individual functions

**Comment by Zamiell** [comment]
so you need to add something to integration.test.ts

and no you dont need to use a JSON, you can just code yourself a simple game state from scratch

**Comment by Zamiell** [comment]
actually

**Comment by Zamiell** [comment]
i dont actually know

**Comment by Zamiell** [comment]
look at how turnReducer.test.ts works, it is a similar thing as statsReducer - both .turn and .stats are sub chunks of the bigger state

**Comment by Zamiell** [comment]
i think you can just copy that to do what you want

**Comment by Zamiell** [comment]
e.g.

```
      const drawAction = draw(0, 0, 0, 1); // Draw a red 1
      state = turnReducer(state, drawAction, defaultGameState, defaultMetadata);

      for (let i = 0; i < 3; i++) {
        const playAction = play(0, i, 0, 1); // Play the last red 1 that was drawn
        state = turnReducer(
          state,
          playAction,
          defaultGameState,
          defaultMetadata,
        );
        const drawAction2 = draw(0, i + 1, 0, 1); // Draw another red 1
        state = turnReducer(
          state,
          drawAction2,
          defaultGameState,
          defaultMetadata,
        );
      }
```

**Comment by timotree3** [comment]
Just debugged. future efficiency number dips easier for a moment until the draw action reduces and it goes back to normal every time that a play or discard occurs

**Comment by timotree3** [comment]
Why doesn't that happen the pace?

**Comment by timotree3** [comment]
Debugged the pace and the pace also increase for a moment, it even calls the function that changes the text on the label, and then calls `batchDraw`, but nothing on screen changes and it has time to set it back to normal and call `batchDraw` again. Maybe the problem is the way that `batchDraw` was working? It was drawing part-way through the process and therefore showed a wrong efficiency?

**Comment by timotree3** [comment]
That seems like an unrelated bug so we can probably merge this. The solution to that bug would probably be to change the time at which `cardsRemainingInTheDeck` is changed such that it changes during a `play` or `discard` action instead of during a `draw` action.

**Comment by timotree3** [comment]
another bug found

**Comment by timotree3** [comment]
That one only occurs once a 5 has been played so didn't show up in any tests.

**Comment by Zamiell** [comment]
[ ] add tests for all of the interesting stats functions besides doubleDiscard
[ ] fix pace with contrarian
[ ] fix pace + efficiency with all or nothing

**Comment by Zamiell** [comment]
is #1 done?

**Comment by timotree3** [comment]
No I haven't done those tests and don't want to anymore. I also don't care about all or nothing because that variant is way too easy. I would fix pace with contrarian but I don't see why that should hold up this PR. I'll do that later today as a new PR unless this one hasn't been merged yet.

**Comment by timotree3** [comment]
Okay. added contrarian support.

**Comment by Zamiell** [comment]
looks good thanks!

**Pull request merged**
