### PR TITLE
/levels command, include tagsdeleteall in docs

### LINKED ISSUE #2239: add chat command for https://hanabi.github.io/docs/learning-path#level-summary

### PR DESCRIPTION
**Pull request by DrAnax**
Closes #2239

### CODE REVIEW

**Comment by Zamiell** [comment]
can you also make /learningpath

**Comment by DrAnax** [comment]
> can you also make /learningpath

Same link?

**Comment by Zamiell** [comment]
yes just have it by a synonym

**Comment by Zamiell** [comment]
also /path

**Comment by Zamiell** [comment]
dont include the aliases in the documentation, its too much

**Comment by Zamiell** [comment]
(none of the other aliases are in the documentation by design)

**Comment by Zamiell** [comment]
thanks

**Comment by Aigul9** [comment]
ty, takis

**Pull request merged**
