### PR TITLE
Show max rounds left and other statistics on turn number hover

### LINKED ISSUE #1825: feature: statistic showing max rounds left
This would be useful in the endgame for determining whether someone has enough time to play all their cards or needs a tempo clue.

Formula is: cluesStillUsable + pace + missing score = max turns left
max rounds left = max turns left / numPlayers

### PR DESCRIPTION
**Pull request by timotree3**
Resolves #1825 
image

### CODE REVIEW

**Comment by timotree3** [comment]
This sometimes overestimates the amount of turns left due to #1847

**Comment by Zamiell** [comment]
isn't the 3rd line superfluous?

**Comment by timotree3** [comment]
No?
Screenshot from 2020-11-17 18-23-19

**Comment by Zamiell** [comment]
why does it say 5 total turns if it is currently turn 6?

**Comment by timotree3** [comment]
Because 5 turns has passed. Turn 6 has yet to be taken.

**Comment by Zamiell** [comment]
k

**Comment by Zamiell** [comment]
can you align the numbers like i do in the other tooltips

**Comment by timotree3** [comment]
Screenshot from 2020-11-17 18-32-22

**Comment by Zamiell** [comment]
better)

**Comment by Zamiell** [comment]
thanks

**Pull request merged**
