### PR TITLE
Implement #1760

### PR DESCRIPTION
**Pull request by vEnhance**
Implement #1760 

At start of game, send a chat saying "<username> created a table".

### CODE REVIEW

**Comment by Zamiell** [comment]
use the linter like it says in install.md

**Comment by vEnhance** [comment]
> use the linter like it says in install.md

Haha I tried for half an hour to get the server linter to work on my desktop but couldn't, so I just jumped the gun and tried to let travis do the linting for me. Didn't think it would actually fail.

I'll go back to trying to figure out why the install linter command won't work

**Comment by Zamiell** [comment]
it works for me on a fresh ubuntu 20

**Comment by vEnhance** [comment]
> it works for me on a fresh ubuntu 20

Yeah I figured it was a local problem. I don't expect you to help me fix my computer for me, but I'll put the error I'm getting here just on the off-chance that someone has seen it before and knows. Will keep trying stuff in the meantime.

```
WARN [runner] Can't run linter unused: buildir: failed to load package : could not load export data: no export data for "github.com/Zamiell/go-logging" 
ERRO Running error: buildir: failed to load package : could not load export data: no export data for "github.com/Zamiell/go-logging" 
```

I'm on arch linux.

**Pull request merged**
