### PR TITLE
Throw-it-in-a-Hole efficiency

### LINKED ISSUE #1888: Effeciency false in Throw it in a Hole
The effeciency required is sometimes shown (during a whole turn) while it shouldn't (but the number shown is really high, things like 3.00/x in a normal game).

### PR DESCRIPTION
**Pull request by timotree3**
Probably fixes #1888

### CODE REVIEW

**Comment by Zamiell** [comment]
Why are we auto formatting tasks

**Comment by timotree3** [comment]
Whenever I run the task that Hyphen created, VSCode edits that file. So I figured I would commit it's change.

**Comment by Hyphen-ated** [comment]
all has been foreseen https://discord.com/channels/140016142600241152/333680903748321282/779802457022136350

**Comment by Hyphen-ated** [comment]
trailing commas are invalid json btw

**Comment by Zamiell** [comment]
> trailing commas are invalid json btw

all vscode json files use the jsonc format:
https://code.visualstudio.com/docs/languages/json
so yes, trailing commas are valid

> Whenever I run the task that Hyphen created, VSCode edits that file. So I figured I would commit it's change.

ok, that is fair

**Comment by Zamiell** [comment]
thanks timo for your work

**Pull request merged**
