### PR TITLE
Update example_game_with_comments.jsonc

### PR DESCRIPTION
**Pull request by akhti**
Make the file loadable (after removing comments)
Fix bugs in the comments
Make deck have 50 cards

I still can only replay the first move, but at least it shows the table

### CODE REVIEW

**Comment by Zamiell** [comment]
thx

**Comment by Zamiell** [comment]
you're from FB?

**Comment by akhti** [comment]
> you're from FB?

yup

**Comment by Zamiell** [comment]
cool thanks

**Pull request merged**
