### PR TITLE
Add dump_game.py for dumping game records

### PR DESCRIPTION
**Pull request by nealmcb**
Still lots more features to add, and ideas to describe for improving game record format, but here's a start.

### CODE REVIEW

**Comment by Zamiell** [comment]
this converts JSON to human-readable format? that doesn't strike me as particularly useful.
if you want a human readable output of a game, is it better to just extend the real API, e.g. `hanabi.live/export/123456/human`

**Comment by nealmcb** [comment]
It would indeed also be useful to have the API generate other forms of human readable output.

But my ultimate goal is different. I see this PR as an early step in establishing an interoperable ecosystem for exploring Hanabi games among humans and AI agents, for integrating with hhttps://github.com/deepmind/hanabi-learning-environment et al.  I think we need to first firm up a robust, interoperable game record format, and that format needs utilities for dumping games, importing them into other systems, analyzing them, etc.

I know Python, not Go, so I'm doing what I can in Python.

I made it a PR here since so far it is specific to the hanabi-live format, and so at least people would be able to find it.

Of course, if you don't want to merge it, it could eventually live elsewhere.

**Comment by Zamiell** [comment]
>I think we need to first firm up a robust, interoperable game record format
Do you see any current issues with the current game record format used in the Hanabi Live export API?

**Comment by Zamiell** [comment]
> I know Python, not Go, so I'm doing what I can in Python.

Ok, but I mean even without knowing Go it would be pretty trivial to create the human API output, just copy paste the existing function and change how it is printed out.

**Pull request merged**
