### PR TITLE
Hide starting player's hand in hypo (#2069)

### LINKED ISSUE #2069: automatically hide cards from hypo holder's hand
Issue opened by Discord user: Zamiel#8743

### PR DESCRIPTION
**Pull request by DrAnax**
Closes #2069

### CODE REVIEW

**Comment by Zamiell** [comment]
horray, this is a very nice PR!

**Comment by DrAnax** [comment]
> horray, this is a very nice PR!

was also a bitch to find and change

**Comment by Zamiell** [comment]
yes, its good for you to get familiar with how the reducers work, as this is the core hanabi logic code

**Comment by DrAnax** [comment]
> yes, its good for you to get familiar with how the reducers work, as this is the core hanabi logic code

I'm grateful this codebase makes me a better person

**Pull request merged**
