### PR TITLE
proper 12pm hour timestamp

### LINKED ISSUE #2087: In-Game chat's Timestamp for messages is inaccurate
In In-Game chat, the time stamp next to player name shows [24:XX] instead of [00:XX].

### PR DESCRIPTION
**Pull request by DrAnax**
Closes #2087

### CODE REVIEW

**Comment by Zamiell** [comment]
can you search codebase for other `DateTimeFormat`?
i believe there are several places with this code, maybe you can unify it

**Comment by DrAnax** [comment]
sure, hold on

**Comment by DrAnax** [comment]
There are but this is the only place where hour format is required

**Comment by Zamiell** [comment]
ok, thanks

**Pull request merged**
